// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// Validation helpers for CliArgumentParser to ensure parsed arguments meet requirements
//
// Generated by automated task - do not modify manually
// =====================================================================

using System;
using System.Collections.Generic;
using System.Globalization;

namespace YouTubeShortsAutomator.CLI;

/// <summary>
/// Provides validation helpers for <see cref="CliArgumentParser"/> parsed arguments
/// </summary>
public static class CliArgumentParserValidation
{
    /// <summary>
    /// Validates that the parsed CLI arguments meet all requirements
    /// </summary>
    /// <param name="value">The parsed CLI arguments to validate</param>
    /// <returns>List of validation problems (empty if valid)</returns>
    /// <exception cref="ArgumentNullException"><paramref name="value"/> is null</exception>
    public static IReadOnlyList<string> Validate(this ParsedCliArguments value)
    {
        ArgumentNullException.ThrowIfNull(value);

        var problems = new List<string>();

        // Validate command is not empty
        if (string.IsNullOrWhiteSpace(value.Command))
        {
            problems.Add("Command cannot be null or empty");
        }

        // Validate required options are present
        // Note: Actual required options validation happens during parsing in CliArgumentParser
        // This is a defensive check for any required options that might be tracked elsewhere

        // Validate positional arguments if needed
        if (value.PositionalArguments.Count > 0)
        {
            for (int i = 0; i < value.PositionalArguments.Count; i++)
            {
                if (string.IsNullOrWhiteSpace(value.PositionalArguments[i]))
                {
                    problems.Add($"Positional argument at index {i} cannot be null or empty");
                }
            }
        }

        // Validate options dictionary
        if (value.Options == null)
        {
            problems.Add("Options dictionary cannot be null");
        }
        else
        {
            foreach (var option in value.Options)
            {
                if (string.IsNullOrWhiteSpace(option.Key))
                {
                    problems.Add("Option key cannot be null or empty");
                }

                if (option.Value == null)
                {
                    problems.Add($"Option '{option.Key}' value cannot be null");
                }
            }
        }

        return problems.AsReadOnly();
    }

    /// <summary>
    /// Checks if the parsed CLI arguments are valid
    /// </summary>
    /// <param name="value">The parsed CLI arguments to check</param>
    /// <returns>True if valid, false otherwise</returns>
    /// <exception cref="ArgumentNullException"><paramref name="value"/> is null</exception>
    public static bool IsValid(this ParsedCliArguments value)
    {
        return Validate(value).Count == 0;
    }

    /// <summary>
    /// Ensures that the parsed CLI arguments are valid, throwing an exception if not
    /// </summary>
    /// <param name="value">The parsed CLI arguments to validate</param>
    /// <exception cref="ArgumentNullException"><paramref name="value"/> is null</exception>
    /// <exception cref="ArgumentException">Arguments are invalid with detailed error messages</exception>
    public static void EnsureValid(this ParsedCliArguments value)
    {
        ArgumentNullException.ThrowIfNull(value);

        var problems = Validate(value);

        if (problems.Count > 0)
        {
            throw new ArgumentException(
                $"Parsed CLI arguments are invalid:{Environment.NewLine}{string.Join(Environment.NewLine, problems)}");
        }
    }
}
