// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// Extension methods for CliArgumentParser to simplify common CLI operations
//
// Generated by automated task - do not modify manually
// =============================================================================

using System;
using System.Collections.Generic;
using System.Globalization;

namespace YouTubeShortsAutomator.CLI;

/// <summary>
/// Provides extension methods for <see cref="CliArgumentParser"/> to simplify common CLI operations
/// </summary>
public static class CliArgumentParserExtensions
{
    /// <summary>
    /// Creates a new command registration with fluent API for building command configuration
    /// </summary>
    /// <param name="parser">The parser instance</param>
    /// <param name="commandName">Name of the command</param>
    /// <param name="description">Command description</param>
    /// <returns>Fluent command builder for method chaining</returns>
    /// <exception cref="ArgumentNullException"><paramref name="parser"/> is null</exception>
    /// <exception cref="ArgumentException"><paramref name="commandName"/> is null or empty</exception>
    public static CliCommandBuilder RegisterCommand(
        this CliArgumentParser parser,
        string commandName,
        string description)
    {
        ArgumentNullException.ThrowIfNull(parser);
        ArgumentException.ThrowIfNullOrEmpty(commandName);

        var command = new CliCommand
        {
            Description = description
        };

        parser.RegisterCommand(commandName, command);
        return new CliCommandBuilder(parser, commandName, command);
    }

    /// <summary>
    /// Parses arguments and automatically handles help/version flags
    /// </summary>
    /// <param name="parser">The parser instance</param>
    /// <param name="args">Command line arguments</param>
    /// <param name="result">Parsed arguments if successful</param>
    /// <param name="showHelpOnError">Whether to display help on parsing failure</param>
    /// <returns>True if parsing succeeded, false otherwise</returns>
    /// <exception cref="ArgumentNullException"><paramref name="parser"/> is null</exception>
    /// <exception cref="ArgumentNullException"><paramref name="args"/> is null</exception>
    public static bool TryParseArguments(
        this CliArgumentParser parser,
        string[] args,
        out ParsedCliArguments result,
        bool showHelpOnError = true)
    {
        ArgumentNullException.ThrowIfNull(parser);
        ArgumentNullException.ThrowIfNull(args);

        result = new ParsedCliArguments();

        if (args.Length == 0)
        {
            if (showHelpOnError)
            {
                parser.PrintHelp();
            }
            return false;
        }

        var command = args[0];

        if (command is "--help" or "-h")
        {
            parser.PrintHelp();
            return false;
        }

        if (command is "--version" or "-v")
        {
            Console.WriteLine("YouTube Shorts Automator v1.0");
            return false;
        }

        if (!parser.TryGetCommand(command, out var cliCommand))
        {
            Console.WriteLine($"Unknown command: {command}");
            if (showHelpOnError)
            {
                parser.PrintHelp();
            }
            return false;
        }

        // Parse remaining arguments
        for (int i = 1; i < args.Length; i++)
        {
            var arg = args[i];

            if (arg.StartsWith("--"))
            {
                var parts = arg.Substring(2).Split('=');
                var key = parts[0];
                var value = parts.Length > 1 ? parts[1] : (i + 1 < args.Length ? args[++i] : "true");
                result.Options[key] = value;
            }
            else if (arg.StartsWith("-"))
            {
                var key = arg.Substring(1);
                var value = i + 1 < args.Length ? args[++i] : "true";
                result.Options[key] = value;
            }
            else
            {
                result.PositionalArguments.Add(arg);
            }
        }

        return parser.ValidateArguments(result, cliCommand);
    }

    /// <summary>
    /// Gets the command description from the registered command
    /// </summary>
    /// <param name="parser">The parser instance</param>
    /// <param name="commandName">Name of the registered command</param>
    /// <param name="description">Outputs the description if found</param>
    /// <returns>True if command exists and has description, false otherwise</returns>
    /// <exception cref="ArgumentNullException"><paramref name="parser"/> is null</exception>
    /// <exception cref="ArgumentException"><paramref name="commandName"/> is null or empty</exception>
    public static bool TryGetCommandDescription(
        this CliArgumentParser parser,
        string commandName,
        out string description)
    {
        ArgumentNullException.ThrowIfNull(parser);
        ArgumentException.ThrowIfNullOrEmpty(commandName);

        description = string.Empty;

        if (parser.TryGetCommand(commandName, out var command))
        {
            description = command.Description;
            return true;
        }

        return false;
    }

    /// <summary>
    /// Fluent builder for configuring CLI commands
    /// </summary>
    public sealed class CliCommandBuilder
    {
        private readonly CliArgumentParser _parser;
        private readonly string _commandName;
        private readonly CliCommand _command;

        internal CliCommandBuilder(
            CliArgumentParser parser,
            string commandName,
            CliCommand command)
        {
            _parser = parser;
            _commandName = commandName;
            _command = command;
        }

        /// <summary>
        /// Adds required options to the command
        /// </summary>
        /// <param name="options">Required option names</param>
        /// <returns>Builder instance for method chaining</returns>
        public CliCommandBuilder WithRequiredOptions(params string[] options)
        {
            ArgumentNullException.ThrowIfNull(options);
            _command.RequiredOptions.AddRange(options);
            return this;
        }

        /// <summary>
        /// Adds optional options to the command
        /// </summary>
        /// <param name="options">Optional option names</param>
        /// <returns>Builder instance for method chaining</returns>
        public CliCommandBuilder WithOptionalOptions(params string[] options)
        {
            ArgumentNullException.ThrowIfNull(options);
            _command.OptionalOptions.AddRange(options);
            return this;
        }

        /// <summary>
        /// Sets the command handler
        /// </summary>
        /// <param name="handler">Async handler function</param>
        /// <returns>Builder instance for method chaining</returns>
        public CliCommandBuilder WithHandler(Func<ParsedCliArguments, Task<int>> handler)
        {
            ArgumentNullException.ThrowIfNull(handler);
            _command.Handler = handler;
            return this;
        }

        /// <summary>
        /// Registers the configured command with the parser
        /// </summary>
        public void Build()
        {
            // Command is already registered in RegisterCommand
        }
    }

    // Helper method to access internal command dictionary
    private static bool TryGetCommand(
        this CliArgumentParser parser,
        string commandName,
        out CliCommand command)
    {
        if (parser.GetType().GetProperty("_commands",
            System.Reflection.BindingFlags.NonPublic |
            System.Reflection.BindingFlags.Instance)?.GetValue(parser) is Dictionary<string, CliCommand> commands)
        {
            return commands.TryGetValue(commandName, out command);
        }

        command = null!;
        return false;
    }

    // Helper method to access internal validation
    private static bool ValidateArguments(
        this CliArgumentParser parser,
        ParsedCliArguments args,
        CliCommand command)
    {
        // Validate required options
        foreach (var required in command.RequiredOptions)
        {
            if (!args.Options.ContainsKey(required))
            {
                Console.WriteLine($"Missing required option: --{required}");
                return false;
            }
        }

        return true;
    }

    // Helper method to access internal help printing
    private static void PrintHelp(this CliArgumentParser parser)
    {
        if (parser.GetType().GetMethod("PrintHelp",
            System.Reflection.BindingFlags.NonPublic |
            System.Reflection.BindingFlags.Instance)?.Invoke(parser, null) is null)
        {
            Console.WriteLine("YouTube Shorts Automator CLI");
            Console.WriteLine("============================");
            Console.WriteLine();
            Console.WriteLine("Usage: youtube-shorts-automator [command] [options]");
            Console.WriteLine();
            Console.WriteLine("Available commands:");
            Console.WriteLine("  help              Show help information");
            Console.WriteLine("  version           Show version information");
        }
    }
}