// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
//
// Validation helpers for AnalyticsController type
//
// Generated by automated task - do not modify manually
// =============================================================================

using System;
using System.Collections.Generic;

namespace YouTubeShortsAutomator.API;

/// <summary>
/// Provides validation helpers for AnalyticsController
/// </summary>
public static class AnalyticsControllerExtensionsValidation
{
    /// <summary>
    /// Validates an AnalyticsController instance and returns any validation problems
    /// </summary>
    /// <param name="value">The AnalyticsController instance to validate</param>
    /// <returns>List of validation problems; empty list if valid</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="value"/> is null</exception>
    public static IReadOnlyList<string> Validate(this AnalyticsController value)
    {
        ArgumentNullException.ThrowIfNull(value);

        var problems = new List<string>();

        // AnalyticsController has no public properties to validate
        // All validation is done on method parameters at runtime

        return problems.AsReadOnly();
    }

    /// <summary>
    /// Checks if an AnalyticsController instance is valid
    /// </summary>
    /// <param name="value">The AnalyticsController instance to check</param>
    /// <returns>True if valid; false otherwise</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="value"/> is null</exception>
    public static bool IsValid(this AnalyticsController value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return true; // AnalyticsController has no public properties to validate
    }

    /// <summary>
    /// Ensures an AnalyticsController instance is valid, throwing an exception if not
    /// </summary>
    /// <param name="value">The AnalyticsController instance to validate</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="value"/> is null</exception>
    /// <exception cref="ArgumentException">Thrown when validation fails</exception>
    public static void EnsureValid(this AnalyticsController value)
    {
        ArgumentNullException.ThrowIfNull(value);
        // AnalyticsController has no public properties to validate
    }
}